### ISSUE TITLE
RuntimeError when training SwinDRNet

### ISSUE THREAD

**Issue by hit421** [PKU-EPIC/DREDS#3]
Hi! I met problem when I was training SwinDRNet. It looks related to inplace operation. My env is Pytorch1.12 with Python3.9.
```shell
Traceback (most recent call last):                                                                                                            
  File "/home/yyy/DC/DREDS/SwinDRNet/train.py", line 110, in <module>                                                             
    _trainer.train()                                                                                                                       
  File "/home/yyy/DC/DREDS/SwinDRNet/trainer.py", line 699, in train                                                                        
    self.loss_train_iter.backward()                                                                                                       
  File "/home/yyy/anaconda3/envs/pt/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward                                  
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)                                                  
  File "/home/yyy/anaconda3/envs/pt/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward                      
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                                     
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 512, 
14, 14]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operatio
n that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck! 
```

**Comment by Daiqy** [comment]
Hi hit421! Please follow our environment setup as shown in [https://github.com/PKU-EPIC/DREDS/tree/main/SwinDRNet#setup](https://github.com/PKU-EPIC/DREDS/tree/main/SwinDRNet#setup) . Thanks!
